<?php

namespace Pdik\LaravelExactOnline;

use Illuminate\Support\ServiceProvider;
use Illuminate\Routing\Router;

class LaravelExactOnlineServiceProvider extends ServiceProvider
{
    public function boot()
    {

        $this->registerConfigs();
        $this->registerViews();
        $this->registerRoutes();
    }
    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }

    private function registerConfigs()
    {
        if ($this->app->runningInConsole()) {
            $this->publishes([
                __DIR__ . '/../config/exact.php' => config_path('exact.php'),
            ], 'laravelExactonlineConfig');

        }
        $this->mergeConfigFrom(__DIR__ . '/../config/exact.php', 'laravelExactonline');

    }

    private function registerViews()
    {
        $this->loadViewsFrom(__DIR__ . '/../resources/views', 'laravelExactonline');
    }

    private function registerRoutes()
    {
      //  $this->loadRoutesFrom(__DIR__.'/../routes/web.php');
        $router = $this->app->make(Router::class);
        $router->group($this->routeConfiguration(), function () {
            $this->loadRoutesFrom(__DIR__ . '/../routes/web.php');
        });
    }

    private function routeConfiguration(): array
    {
        return [
            'namespace' => 'Pdik\laravelexactonline\Http\Controllers',
            'middleware' => ['web'],
            'as' => 'laravelExactonline::',
        ];
    }

}