<?php

namespace Pdik\LaravelExactOnline;

use Illuminate\Support\ServiceProvider;
use Illuminate\Routing\Router;

class LaravelExactOnlineServiceProvider extends ServiceProvider
{
    public function boot()
    {
        $this->registerConfigs();
        $this->registerViews();
        $this->registerRoutes();
    }
    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
        $this->app->register(EventServiceProvider::class);
    }

    private function registerConfigs()
    {
        if ($this->app->runningInConsole()) {
            $this->publishes([
                __DIR__ . '/../config/exact.php' => config_path('exact.php'),
            ], 'exact');

        }
        $this->mergeConfigFrom(__DIR__ . '/../config/exact.php', 'exact');

    }

    private function registerViews()
    {
        $this->loadViewsFrom(__DIR__ . '/../resources/views', 'laravelExactonline');
    }

    private function registerRoutes()
    {
        $this->app->register(RouteServiceProvider::class);
    }

    private function routeConfiguration(): array
    {
        return [
            'namespace' => 'Pdik\laravelexactonline\Http\Controllers',
            'middleware' => ['web'],
            'as' => 'laravelExactonline::',
        ];
    }

}